"""empty message

Revision ID: 77a03963e66c
Revises: de27d0d41efb
Create Date: 2018-12-06 23:34:22.589721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a03963e66c'
down_revision = 'de27d0d41efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_type_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_type_names',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_type_id', sa.INTEGER(), nullable=True),
    sa.Column('task_type_name', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
